<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net9.0-windows;net8.0-windows;net472</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ColumnHeaderCursor.cur" />
    <EmbeddedResource Include="Resources\SheetCursor.cur" />
    <EmbeddedResource Include="Resources\DragFillCursor.cur" />
    <EmbeddedResource Include="Resources\RowHeaderCursor.cur" />
    <EmbeddedResource Include="Resources\ColumnResizeCursor.cur" />
    <EmbeddedResource Include="Resources\RowResizeCursor.cur" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>DevBrewLabs.WPF.Spreadsheet</PackageId>
    <Version>1.0.2</Version>
    <Authors>DevBrewLabs</Authors>
    <Company>DevBrewLabs</Company>
    <Description>High-performance virtualized WPF spreadsheet and grid component.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/dotdevkartik/DevBrewLabs.WPF.Spreadsheet</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageTags>excel;spread;sheet;spreadsheet;grid;datagrid;speed;virtual;wpf grid;cells;columns;rows;</PackageTags>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <SignAssembly>False</SignAssembly>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevBrewLabs.Spreadsheet\DevBrewLabs.Spreadsheet.csproj" PrivateAssets="all" />
    <PackageReference Include="DevBrewLabs.Evalis" Version="1.0.1" />
  </ItemGroup>

  <Target Name="CopyProjectReferencesToPackage">
    <ItemGroup>
      <BuildOutputInPackage Include="$(OutputPath)DevBrewLabs.Spreadsheet.dll" />
      <BuildOutputInPackage Include="$(OutputPath)DevBrewLabs.Spreadsheet.pdb" Condition="Exists('$(OutputPath)DevBrewLabs.Spreadsheet.pdb')" />
      <BuildOutputInPackage Include="$(OutputPath)DevBrewLabs.Spreadsheet.xml" Condition="Exists('$(OutputPath)DevBrewLabs.Spreadsheet.xml')" />
      <BuildOutputInPackage Include="$(OutputPath)DevBrewLabs.Spreadsheet.CalcEngine.dll" />
      <BuildOutputInPackage Include="$(OutputPath)DevBrewLabs.Spreadsheet.CalcEngine.pdb" Condition="Exists('$(OutputPath)DevBrewLabs.Spreadsheet.CalcEngine.pdb')" />
      <BuildOutputInPackage Include="$(OutputPath)DevBrewLabs.Spreadsheet.CalcEngine.xml" Condition="Exists('$(OutputPath)DevBrewLabs.Spreadsheet.CalcEngine.xml')" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="Icon.png" Pack="true" PackagePath="\" />
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>